version: 3

silent: true

vars:
  DAY: 8

tasks:
  default:
    - echo "** Day{{.DAY}} **"
    - deno run --allow-read ./src/day{{.DAY}}/mod.ts
  test:
    - deno test --allow-read
  _args:
    - echo "** Day{{.CLI_ARGS}} **"
    - deno run --allow-read --allow-write ./src/day{{.CLI_ARGS}}/mod.ts
  all:
    - echo -e "==== Advent of Code 2023 ====\n"
    - bash -c 'for i in {1..{{.DAY}}}; do task _args -- $i; echo ""; done'
  day:
    - echo "** Hello, Day{{.DAY}} **"
    - mkdir -p ./src/day{{.DAY}}
    - cp -n ./src/template/* ./src/day{{.DAY}}/
