version: 3

silent: true

vars:
  DAY: 4

tasks:
  default:
    cmds:
      - echo "** Day{{.DAY}} **"
      - deno run --allow-read --allow-write ./src/day{{.DAY}}/mod.ts
  test:
    cmds:
      - deno test --allow-read